import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import JSZip from 'jszip'

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const project = await prisma.project.findFirst({
    where: { id, userId: session.user.id },
    include: { files: true },
  })

  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 })
  }

  if (project.files.length === 0) {
    return NextResponse.json({ error: 'No files to export' }, { status: 400 })
  }

  const zip = new JSZip()
  for (const file of project.files) {
    zip.file(file.path, file.content)
  }

  // Add a README
  zip.file(
    'README.md',
    `# ${project.name}\n\nGenerated by Pi Website Builder\n\nCreated: ${new Date(project.createdAt).toLocaleDateString()}\n`
  )

  const buffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' })

  const safeName = project.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .substring(0, 50)

  const uint8 = new Uint8Array(buffer)

  return new Response(uint8, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeName}.zip"`,
      'Content-Length': uint8.length.toString(),
    },
  })
}
