export interface ColorPalette {
  id: string
  name: string
  emoji: string
  description: string
  category: 'cool' | 'warm' | 'nature' | 'bold' | 'neutral' | 'dark' | 'pastel'
  colors: {
    primary: string
    primaryDark: string
    accent: string
    text: string
    textSecondary: string
    textMuted: string
    bg: string
    bgCard: string
    bgSection: string
    border: string
  }
}

export const COLOR_PALETTES: ColorPalette[] = [
  // Cool (5)
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    emoji: '🌊',
    description: 'Fresh and professional with deep ocean tones',
    category: 'cool',
    colors: {
      primary: '#0EA5E9',
      primaryDark: '#0284C7',
      accent: '#38BDF8',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      bg: '#FFFFFF',
      bgCard: '#F8FAFC',
      bgSection: '#F1F5F9',
      border: '#E2E8F0',
    },
  },
  {
    id: 'arctic-ice',
    name: 'Arctic Ice',
    emoji: '🧊',
    description: 'Cool indigo with icy highlights',
    category: 'cool',
    colors: {
      primary: '#6366F1',
      primaryDark: '#4F46E5',
      accent: '#A5B4FC',
      text: '#111827',
      textSecondary: '#4B5563',
      textMuted: '#9CA3AF',
      bg: '#FAFAFA',
      bgCard: '#FFFFFF',
      bgSection: '#F3F4F6',
      border: '#E5E7EB',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    emoji: '🌃',
    description: 'Deep navy with bright blue accents on dark background',
    category: 'cool',
    colors: {
      primary: '#1E3A8A',
      primaryDark: '#1E40AF',
      accent: '#60A5FA',
      text: '#F9FAFB',
      textSecondary: '#E5E7EB',
      textMuted: '#9CA3AF',
      bg: '#030712',
      bgCard: '#0F172A',
      bgSection: '#1E293B',
      border: '#334155',
    },
  },
  {
    id: 'steel-blue',
    name: 'Steel Blue',
    emoji: '🔩',
    description: 'Industrial slate with cool blue tones',
    category: 'cool',
    colors: {
      primary: '#334155',
      primaryDark: '#1E293B',
      accent: '#64748B',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      bg: '#F8FAFC',
      bgCard: '#FFFFFF',
      bgSection: '#F1F5F9',
      border: '#CBD5E1',
    },
  },
  {
    id: 'cerulean',
    name: 'Cerulean',
    emoji: '💎',
    description: 'Bright cyan with deep blue foundation',
    category: 'cool',
    colors: {
      primary: '#0369A1',
      primaryDark: '#0C4A6E',
      accent: '#7DD3FC',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      bg: '#FFFFFF',
      bgCard: '#F0F9FF',
      bgSection: '#E0F2FE',
      border: '#BAE6FD',
    },
  },

  // Warm (5)
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    emoji: '🌅',
    description: 'Vibrant orange with warm golden undertones',
    category: 'warm',
    colors: {
      primary: '#EA580C',
      primaryDark: '#C2410C',
      accent: '#FB923C',
      text: '#0F172A',
      textSecondary: '#78350F',
      textMuted: '#92400E',
      bg: '#FFFBF5',
      bgCard: '#FFFFFF',
      bgSection: '#FFF7ED',
      border: '#FDBA74',
    },
  },
  {
    id: 'cherry-red',
    name: 'Cherry Red',
    emoji: '🍒',
    description: 'Bold red with soft pink accents',
    category: 'warm',
    colors: {
      primary: '#DC2626',
      primaryDark: '#B91C1C',
      accent: '#F87171',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      bg: '#FFFFFF',
      bgCard: '#FEF2F2',
      bgSection: '#FEE2E2',
      border: '#FECACA',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    emoji: '🌹',
    description: 'Elegant rose with metallic gold shimmer',
    category: 'warm',
    colors: {
      primary: '#E11D48',
      primaryDark: '#BE123C',
      accent: '#FDA4AF',
      text: '#0F172A',
      textSecondary: '#881337',
      textMuted: '#9F1239',
      bg: '#FFF1F2',
      bgCard: '#FFFFFF',
      bgSection: '#FFE4E6',
      border: '#FECDD3',
    },
  },
  {
    id: 'amber-honey',
    name: 'Amber Honey',
    emoji: '🍯',
    description: 'Rich amber with golden honey glow',
    category: 'warm',
    colors: {
      primary: '#D97706',
      primaryDark: '#B45309',
      accent: '#FCD34D',
      text: '#0F172A',
      textSecondary: '#78350F',
      textMuted: '#92400E',
      bg: '#FFFBEB',
      bgCard: '#FFFFFF',
      bgSection: '#FEF3C7',
      border: '#FDE68A',
    },
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    emoji: '🏺',
    description: 'Earthy clay with warm orange highlights',
    category: 'warm',
    colors: {
      primary: '#C2410C',
      primaryDark: '#9A3412',
      accent: '#FB923C',
      text: '#0F172A',
      textSecondary: '#7C2D12',
      textMuted: '#9A3412',
      bg: '#FFF7ED',
      bgCard: '#FFFFFF',
      bgSection: '#FFEDD5',
      border: '#FED7AA',
    },
  },

  // Nature (5)
  {
    id: 'forest-green',
    name: 'Forest Green',
    emoji: '🌲',
    description: 'Deep forest green with fresh spring accents',
    category: 'nature',
    colors: {
      primary: '#16A34A',
      primaryDark: '#15803D',
      accent: '#4ADE80',
      text: '#0F172A',
      textSecondary: '#14532D',
      textMuted: '#166534',
      bg: '#F0FDF4',
      bgCard: '#FFFFFF',
      bgSection: '#DCFCE7',
      border: '#BBF7D0',
    },
  },
  {
    id: 'sage-mist',
    name: 'Sage Mist',
    emoji: '🌿',
    description: 'Soft sage with lime green energy',
    category: 'nature',
    colors: {
      primary: '#4D7C0F',
      primaryDark: '#3F6212',
      accent: '#A3E635',
      text: '#0F172A',
      textSecondary: '#365314',
      textMuted: '#3F6212',
      bg: '#F7FEE7',
      bgCard: '#FFFFFF',
      bgSection: '#ECFCCB',
      border: '#D9F99D',
    },
  },
  {
    id: 'earth-brown',
    name: 'Earth Brown',
    emoji: '🌍',
    description: 'Rich soil brown with amber warmth',
    category: 'nature',
    colors: {
      primary: '#92400E',
      primaryDark: '#78350F',
      accent: '#D97706',
      text: '#0F172A',
      textSecondary: '#78350F',
      textMuted: '#92400E',
      bg: '#FFFBEB',
      bgCard: '#FFFFFF',
      bgSection: '#FEF3C7',
      border: '#FDE68A',
    },
  },
  {
    id: 'lavender-bloom',
    name: 'Lavender Bloom',
    emoji: '💜',
    description: 'Delicate lavender with purple bloom',
    category: 'nature',
    colors: {
      primary: '#7C3AED',
      primaryDark: '#6D28D9',
      accent: '#C4B5FD',
      text: '#0F172A',
      textSecondary: '#5B21B6',
      textMuted: '#6D28D9',
      bg: '#F5F3FF',
      bgCard: '#FFFFFF',
      bgSection: '#EDE9FE',
      border: '#DDD6FE',
    },
  },
  {
    id: 'teal-forest',
    name: 'Teal Forest',
    emoji: '🦚',
    description: 'Deep teal with turquoise shimmer',
    category: 'nature',
    colors: {
      primary: '#0F766E',
      primaryDark: '#115E59',
      accent: '#2DD4BF',
      text: '#0F172A',
      textSecondary: '#134E4A',
      textMuted: '#115E59',
      bg: '#F0FDFA',
      bgCard: '#FFFFFF',
      bgSection: '#CCFBF1',
      border: '#99F6E4',
    },
  },

  // Bold (5)
  {
    id: 'electric-purple',
    name: 'Electric Purple',
    emoji: '⚡',
    description: 'Vibrant purple with electric energy',
    category: 'bold',
    colors: {
      primary: '#9333EA',
      primaryDark: '#7E22CE',
      accent: '#D8B4FE',
      text: '#0F172A',
      textSecondary: '#6B21A8',
      textMuted: '#7E22CE',
      bg: '#FAF5FF',
      bgCard: '#FFFFFF',
      bgSection: '#F3E8FF',
      border: '#E9D5FF',
    },
  },
  {
    id: 'neon-green',
    name: 'Neon Green',
    emoji: '🟢',
    description: 'Bright neon green on deep dark background',
    category: 'bold',
    colors: {
      primary: '#16A34A',
      primaryDark: '#15803D',
      accent: '#86EFAC',
      text: '#F0FDF4',
      textSecondary: '#BBF7D0',
      textMuted: '#86EFAC',
      bg: '#052E16',
      bgCard: '#14532D',
      bgSection: '#166534',
      border: '#15803D',
    },
  },
  {
    id: 'hot-pink',
    name: 'Hot Pink',
    emoji: '🩷',
    description: 'Bold fuchsia with soft pink highlights',
    category: 'bold',
    colors: {
      primary: '#DB2777',
      primaryDark: '#BE185D',
      accent: '#F9A8D4',
      text: '#0F172A',
      textSecondary: '#9F1239',
      textMuted: '#BE185D',
      bg: '#FFF0F7',
      bgCard: '#FFFFFF',
      bgSection: '#FCE7F3',
      border: '#FBCFE8',
    },
  },
  {
    id: 'vibrant-coral',
    name: 'Vibrant Coral',
    emoji: '🪸',
    description: 'Stunning coral on dramatic dark background',
    category: 'bold',
    colors: {
      primary: '#F43F5E',
      primaryDark: '#E11D48',
      accent: '#FDA4AF',
      text: '#FAFAFA',
      textSecondary: '#FECDD3',
      textMuted: '#FDA4AF',
      bg: '#0A0505',
      bgCard: '#1F1315',
      bgSection: '#4C0519',
      border: '#881337',
    },
  },
  {
    id: 'gold-black',
    name: 'Gold Black',
    emoji: '🏆',
    description: 'Luxurious gold on premium black',
    category: 'bold',
    colors: {
      primary: '#CA8A04',
      primaryDark: '#A16207',
      accent: '#FDE68A',
      text: '#FAFAFA',
      textSecondary: '#FEF3C7',
      textMuted: '#FDE68A',
      bg: '#030712',
      bgCard: '#0F172A',
      bgSection: '#1E293B',
      border: '#713F12',
    },
  },

  // Neutral (4)
  {
    id: 'charcoal',
    name: 'Charcoal',
    emoji: '🪨',
    description: 'Professional charcoal gray with subtle depth',
    category: 'neutral',
    colors: {
      primary: '#374151',
      primaryDark: '#1F2937',
      accent: '#6B7280',
      text: '#0F172A',
      textSecondary: '#4B5563',
      textMuted: '#9CA3AF',
      bg: '#FAFAFA',
      bgCard: '#FFFFFF',
      bgSection: '#F3F4F6',
      border: '#E5E7EB',
    },
  },
  {
    id: 'warm-gray',
    name: 'Warm Gray',
    emoji: '🌫️',
    description: 'Soft warm gray with gentle contrast',
    category: 'neutral',
    colors: {
      primary: '#6B7280',
      primaryDark: '#4B5563',
      accent: '#9CA3AF',
      text: '#0F172A',
      textSecondary: '#4B5563',
      textMuted: '#9CA3AF',
      bg: '#FAFAF9',
      bgCard: '#FFFFFF',
      bgSection: '#F5F5F4',
      border: '#E7E5E4',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    emoji: '🪟',
    description: 'Clean slate with cool blue-gray tones',
    category: 'neutral',
    colors: {
      primary: '#475569',
      primaryDark: '#334155',
      accent: '#94A3B8',
      text: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      bg: '#F8FAFC',
      bgCard: '#FFFFFF',
      bgSection: '#F1F5F9',
      border: '#E2E8F0',
    },
  },
  {
    id: 'zinc',
    name: 'Zinc',
    emoji: '⚙️',
    description: 'Modern zinc with metallic neutrality',
    category: 'neutral',
    colors: {
      primary: '#52525B',
      primaryDark: '#3F3F46',
      accent: '#A1A1AA',
      text: '#0F172A',
      textSecondary: '#52525B',
      textMuted: '#A1A1AA',
      bg: '#FAFAFA',
      bgCard: '#FFFFFF',
      bgSection: '#F4F4F5',
      border: '#E4E4E7',
    },
  },

  // Dark (3)
  {
    id: 'void-black',
    name: 'Void Black',
    emoji: '🕳️',
    description: 'Pure black void with indigo highlights',
    category: 'dark',
    colors: {
      primary: '#6366F1',
      primaryDark: '#4F46E5',
      accent: '#818CF8',
      text: '#FAFAFA',
      textSecondary: '#E5E7EB',
      textMuted: '#A1A1AA',
      bg: '#000000',
      bgCard: '#0A0A0A',
      bgSection: '#18181B',
      border: '#27272A',
    },
  },
  {
    id: 'dark-emerald',
    name: 'Dark Emerald',
    emoji: '🌑',
    description: 'Emerald green glowing in darkness',
    category: 'dark',
    colors: {
      primary: '#10B981',
      primaryDark: '#059669',
      accent: '#34D399',
      text: '#FAFAFA',
      textSecondary: '#D1FAE5',
      textMuted: '#A7F3D0',
      bg: '#030712',
      bgCard: '#0F172A',
      bgSection: '#1E293B',
      border: '#064E3B',
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    emoji: '🖤',
    description: 'Glossy obsidian with purple sheen',
    category: 'dark',
    colors: {
      primary: '#8B5CF6',
      primaryDark: '#7C3AED',
      accent: '#A78BFA',
      text: '#FAFAFA',
      textSecondary: '#E9D5FF',
      textMuted: '#C4B5FD',
      bg: '#09090B',
      bgCard: '#18181B',
      bgSection: '#27272A',
      border: '#3F3F46',
    },
  },

  // Pastel (3)
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    emoji: '🍬',
    description: 'Sweet pink with dreamy softness',
    category: 'pastel',
    colors: {
      primary: '#EC4899',
      primaryDark: '#DB2777',
      accent: '#F9A8D4',
      text: '#0F172A',
      textSecondary: '#831843',
      textMuted: '#9F1239',
      bg: '#FEF3F8',
      bgCard: '#FFFFFF',
      bgSection: '#FCE7F3',
      border: '#FBCFE8',
    },
  },
  {
    id: 'baby-blue',
    name: 'Baby Blue',
    emoji: '🫐',
    description: 'Soft baby blue with gentle sky tones',
    category: 'pastel',
    colors: {
      primary: '#3B82F6',
      primaryDark: '#2563EB',
      accent: '#BFDBFE',
      text: '#0F172A',
      textSecondary: '#1E3A8A',
      textMuted: '#1E40AF',
      bg: '#EFF6FF',
      bgCard: '#FFFFFF',
      bgSection: '#DBEAFE',
      border: '#BFDBFE',
    },
  },
  {
    id: 'mint-cream',
    name: 'Mint Cream',
    emoji: '🍃',
    description: 'Fresh mint with creamy green softness',
    category: 'pastel',
    colors: {
      primary: '#059669',
      primaryDark: '#047857',
      accent: '#A7F3D0',
      text: '#0F172A',
      textSecondary: '#065F46',
      textMuted: '#047857',
      bg: '#ECFDF5',
      bgCard: '#FFFFFF',
      bgSection: '#D1FAE5',
      border: '#A7F3D0',
    },
  },
]

export const PALETTE_CATEGORIES = [
  'All',
  'Cool',
  'Warm',
  'Nature',
  'Bold',
  'Neutral',
  'Dark',
  'Pastel',
] as const

export function getPaletteById(id: string): ColorPalette | undefined {
  return COLOR_PALETTES.find((palette) => palette.id === id)
}
