import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { gemini } from '@/lib/gemini'

// Estimate credit cost (in Pi Credits)
const ESTIMATED_CREDITS = 325 // Based on typical usage

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const user = await prisma.user.findUnique({
      where: { email: session.user?.email! },
    })
    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    // Check credit balance
    if (user.credits < ESTIMATED_CREDITS) {
      return NextResponse.json(
        { error: 'Insufficient credits. Please purchase more.' },
        { status: 402 }
      )
    }

    const { prompt } = await req.json()
    if (!prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 })
    }

    // Create project in database
    const project = await prisma.project.create({
      data: {
        name: `Website: ${prompt.substring(0, 50)}...`,
        description: prompt,
        userId: user.id,
        status: 'GENERATING',
      },
    })

    // Start generation (in background - we'll do it synchronously for now)
    try {
      // Step 1: Planner
      const plan = await gemini.generatePlan(prompt)
      
      // Step 2: Coder
      const code = await gemini.generateCode(plan)
      
      // Step 3: QA & Improvement
      const finalCode = await gemini.reviewAndImprove(code, plan)
      
      // Parse the generated code into files
      // For simplicity, we'll assume it's a single HTML file for now
      const files = [
        {
          name: 'index.html',
          path: 'index.html',
          content: finalCode,
        },
        {
          name: 'styles.css',
          path: 'css/styles.css',
          content: '/* Generated by Pi */\n' + extractCSS(finalCode),
        },
      ]
      
      // Save files to database
      for (const file of files) {
        await prisma.file.create({
          data: {
            name: file.name,
            path: file.path,
            content: file.content,
            projectId: project.id,
          },
        })
      }
      
      // Update project status
      await prisma.project.update({
        where: { id: project.id },
        data: { status: 'DRAFT' },
      })
      
      // Deduct credits (placeholder - we need actual token usage)
      await prisma.user.update({
        where: { id: user.id },
        data: { credits: { decrement: ESTIMATED_CREDITS } },
      })
      
      // Log transaction
      await prisma.tokenTransaction.create({
        data: {
          userId: user.id,
          amount: -ESTIMATED_CREDITS,
          type: 'WEBSITE_GENERATION',
          metadata: { prompt, projectId: project.id },
        },
      })
      
      return NextResponse.json({
        success: true,
        projectId: project.id,
        message: 'Website generated successfully',
      })
      
    } catch (error) {
      // Update project status to failed
      await prisma.project.update({
        where: { id: project.id },
        data: { status: 'DRAFT' }, // Or FAILED
      })
      
      console.error('Generation error:', error)
      return NextResponse.json(
        { error: 'Failed to generate website' },
        { status: 500 }
      )
    }
    
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// Helper to extract CSS from HTML (simplistic)
function extractCSS(html: string): string {
  // This is a placeholder - in reality you'd parse the HTML
  // and extract style tags or Tailwind classes
  return `
  /* Tailwind CSS via CDN */
  @import url('https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css');
  
  /* Custom styles */
  body { font-family: 'Inter', sans-serif; }
  `
}